# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

name: Xamarin.Android Build

trigger:
- master
- azure-pipelines

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Debug'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1
  displayName: Install Nuget Tool

- task: NuGetCommand@2
  displayName: Restore NuGet Packages for Solution
  inputs:
    restoreSolution: '**/*.sln'

- task: DownloadSecureFile@1
  displayName: Download Debug AppSettings File
  name: secureDebugAppFile
  inputs:
    secureFile: 'appsettings.Development.json'

- task: DownloadSecureFile@1
  displayName: Download Release AppSettings File
  name: secureReleaseAppFile
  inputs:
    secureFile: 'appsettings.Production.json'

- task: Bash@3
  displayName: Link the secure file to the correct directory
  inputs:
    targetType: 'inline'
    script: |
      cd KMSCalendar/KMSCalendar/
      cmd <<< "mklink appsettings.Development.json $(secureDebugAppFile.secureFilePath)"
      cmd <<< "mklink appsettings.Production.json $(secureReleaseAppFile.secureFilePath)"

- task: XamarinAndroid@1
  displayName: Build Xamarin.Android Project
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildVersionOption: 'latest'
    msbuildArchitectureOption: 'x64'
    jdkOption: 'JDKVersion'